# Generated by Django 5.0.1 on 2024-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
