# Generated by Django 5.0.1 on 2024-01-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_qty_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
