# Generated by Django 5.0.1 on 2024-01-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_sold',
            field=models.IntegerField(default=0),
        ),
    ]
