# Generated by Django 5.0.1 on 2024-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='media/products/'),
            preserve_default=False,
        ),
    ]
