# Generated by Django 5.0.1 on 2024-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
